[package]
name = "image_viewer"
version = "0.1.0"
authors = ["march101348 <12351235ti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.1.1"
